### ISSUE TITLE
Method compareTo from class LabelSet

### ISSUE THREAD

**Issue by bortega94** [tsoumakas/mulan#15]
See the method compareTo from the class LabelSet the comparison is inverted, works contrary of the original  compareTo of Java. Invert the comparison.
Está al revés de como Java lo implementa. Devuelve -1 si el objeto que se pasa como parámetro es menor que el objeto que llama al método. Sin embargo como lo implementa Java es que devuelve -1 cuando el objeto que llama al método es menor que el parámetro.

**Comment by tsoumakas** [comment]
Can you write this in English?

**Comment by gtzinos** [comment]
FIXED: https://github.com/tsoumakas/mulan/pull/17
