### ISSUE TITLE
Method transformInstances from class BinaryRelevanceTransformation

### ISSUE THREAD

**Issue by bortega94** [tsoumakas/mulan#16]
the other methods transformInstances run well, but see the first static method transformInstances here is inverted the selection of the Remove, and that deletes all except the labels that the method says it removes.

**Comment by tsoumakas** [comment]
Actually, this does not have this effect, as invertion followed setInputFormat. I updated the code (https://github.com/tsoumakas/mulan/commit/dbc118ed4493953336d5b646354399e72bc05aac) to remove the invertion completely and avoid misunderstandings. Thanks for pointing this out.
